import { Word } from "./types";

export const DEFAULT_WORDS: Word[] = [
  {
    id: "w1-1",
    word: "Serendipity",
    pronunciation: "/ˌserənˈdipədē/",
    partOfSpeech: "noun",
    definition: "The occurrence of events by chance in a happy or beneficial way.",
    translation: "Sự tình cờ / Cơ may",
    example: "We found the charming little bookstore by pure serendipity while walking in the rain.",
    exampleTranslation: "Chúng tôi đã tìm thấy một hiệu sách nhỏ xinh xắn nhờ sự tình cờ thuần túy khi đang đi dạo dưới mưa.",
    category: "General / Daily Life",
    context: "Unexpected good luck, joyful discoveries, and happy accidents in daily life.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-2",
    word: "Resilient",
    pronunciation: "/rəˈzilyənt/",
    partOfSpeech: "adjective",
    definition: "Able to withstand or recover quickly from difficult conditions.",
    translation: "Kiên cường / Mau phục hồi",
    example: "Despite facing many setbacks, the young entrepreneur remained resilient and successful.",
    exampleTranslation: "Mặc dù đối mặt với nhiều thất bại, doanh nhân trẻ vẫn giữ vững sự kiên cường và đã thành công.",
    category: "Personal Growth & Work",
    context: "Overcoming challenges, business perseverance, and mental toughness.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-3",
    word: "Articulate",
    pronunciation: "/ärˈtikyələt/",
    partOfSpeech: "adjective",
    definition: "Having or showing the ability to speak fluently and coherently.",
    translation: "Hoạt ngôn / Rõ ràng",
    example: "She gave an articulate speech that clearly explained the company's future strategy.",
    exampleTranslation: "Cô ấy đã có một bài phát biểu rõ ràng, giải thích tường tận chiến lược tương lai của công ty.",
    category: "Communication & Public Speaking",
    context: "Business presentations, clear expression of complex ideas, and fluent speech.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-4",
    word: "Nostalgic",
    pronunciation: "/nəˈstaljik/",
    partOfSpeech: "adjective",
    definition: "Feeling, expressing, or causing a sentimental longing for the past.",
    translation: "Hoài niệm / Nhớ nhung",
    example: "Listening to those old records made me feel nostalgic for my college days.",
    exampleTranslation: "Nghe những đĩa nhạc cũ đó khiến tôi cảm thấy hoài niệm về những ngày học đại học.",
    category: "Emotion & Reflection",
    context: "Reminiscing about childhood, old memories, music, and sentimental places.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-5",
    word: "Empathy",
    pronunciation: "/ˈempəTHē/",
    partOfSpeech: "noun",
    definition: "The ability to understand and share the feelings of another person.",
    translation: "Sự đồng cảm / Thấu cảm",
    example: "Showing empathy to your classmates helps build a supportive learning environment.",
    exampleTranslation: "Thể hiện sự đồng cảm với các bạn cùng lớp giúp xây dựng một môi trường học tập hỗ trợ lẫn nhau.",
    category: "Relationships & Psychology",
    context: "Interpersonal connections, social understanding, and emotional support.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-1",
    word: "Wanderlust",
    pronunciation: "/ˈwändərˌləst/",
    partOfSpeech: "noun",
    definition: "A strong desire to travel and explore the world.",
    translation: "Niềm đam mê xê dịch / Thích du lịch",
    example: "Her wanderlust led her to pack a backpack and explore South America for six months.",
    exampleTranslation: "Niềm đam mê xê dịch đã thôi thúc cô đóng gói ba lô và khám phá Nam Mỹ trong sáu tháng.",
    category: "Travel & Adventure",
    context: "Backpacking trips, international exploration, and passion for new cultures.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-2",
    word: "Itinerary",
    pronunciation: "/īˈtinəˌrerē/",
    partOfSpeech: "noun",
    definition: "A planned route or journey schedule.",
    translation: "Lịch trình chuyến đi",
    example: "We must review our travel itinerary to make sure we don't miss our train connections.",
    exampleTranslation: "Chúng ta phải xem lại lịch trình chuyến đi để chắc chắn rằng không bị lỡ bất kỳ chuyến tàu nào.",
    category: "Travel & Planning",
    context: "Flight schedules, vacation day-by-day plans, and tour bookings.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-3",
    word: "Lodging",
    pronunciation: "/ˈläjiŋ/",
    partOfSpeech: "noun",
    definition: "Temporary place to stay or sleep, such as a hotel or hostel.",
    translation: "Chỗ ở / Nơi lưu trú",
    example: "Finding budget-friendly lodging in the city center can be challenging during peak season.",
    exampleTranslation: "Tìm kiếm chỗ ở hợp túi tiền ở trung tâm thành phố có thể khá khó khăn trong mùa cao điểm.",
    category: "Travel & Hospitality",
    context: "Reserving hotels, hostels, Airbnb rentals, and overnight accommodations.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-4",
    word: "Transit",
    pronunciation: "/ˈtranzət/",
    partOfSpeech: "noun",
    definition: "The carrying of people or goods from one place to another.",
    translation: "Quá cảnh / Trung chuyển",
    example: "Our baggage was lost in transit between Madrid and Rome.",
    exampleTranslation: "Hành lý của chúng tôi đã bị thất lạc trong quá trình trung chuyển giữa Madrid và Rome.",
    category: "Travel & Transportation",
    context: "Airport layovers, public transportation networks, and shipping logistics.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-5",
    word: "Souvenir",
    pronunciation: "/ˌso͞ovəˈnir/",
    partOfSpeech: "noun",
    definition: "A thing that is kept as a reminder of a person, place, or event.",
    translation: "Quà lưu niệm",
    example: "I bought a small model of the Eiffel Tower as a souvenir of my trip to Paris.",
    exampleTranslation: "Tôi đã mua một mô hình nhỏ của tháp Eiffel làm quà lưu niệm cho chuyến đi tới Paris.",
    category: "Travel & Shopping",
    context: "Buying keepsakes, gifts from abroad, and mementos of memorable places.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  }
];
