import { Word } from "./types";

export const DEFAULT_WORDS: Word[] = [
  {
    id: "w1-1",
    word: "Serendipity",
    pronunciation: "/ˌserənˈdipədē/",
    partOfSpeech: "noun",
    definition: "The occurrence of events by chance in a happy or beneficial way.",
    translation: "Serendipia",
    example: "We found the charming little bookstore by pure serendipity while walking in the rain.",
    exampleTranslation: "Encontramos la encantadora librería por pura serendipia mientras caminábamos bajo la lluvia.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-2",
    word: "Resilient",
    pronunciation: "/rəˈzilyənt/",
    partOfSpeech: "adjective",
    definition: "Able to withstand or recover quickly from difficult conditions.",
    translation: "Resiliente",
    example: "Despite facing many setbacks, the young entrepreneur remained resilient and successful.",
    exampleTranslation: "A pesar de enfrentar muchos contratiempos, el joven empresario se mantuvo resiliente y exitoso.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-3",
    word: "Articulate",
    pronunciation: "/ärˈtikyələt/",
    partOfSpeech: "adjective",
    definition: "Having or showing the ability to speak fluently and coherently.",
    translation: "Articulado / Elocuente",
    example: "She gave an articulate speech that clearly explained the company's future strategy.",
    exampleTranslation: "Ella dio un discurso elocuente que explicó claramente la estrategia futura de la empresa.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-4",
    word: "Nostalgic",
    pronunciation: "/nəˈstaljik/",
    partOfSpeech: "adjective",
    definition: "Feeling, expressing, or causing a sentimental longing for the past.",
    translation: "Nostálgico",
    example: "Listening to those old records made me feel nostalgic for my college days.",
    exampleTranslation: "Escuchar esos discos viejos me hizo sentir nostálgico por mis días universitarios.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w1-5",
    word: "Empathy",
    pronunciation: "/ˈempəTHē/",
    partOfSpeech: "noun",
    definition: "The ability to understand and share the feelings of another person.",
    translation: "Empatía",
    example: "Showing empathy to your classmates helps build a supportive learning environment.",
    exampleTranslation: "Mostrar empatía hacia tus compañeros ayuda a construir un entorno de aprendizaje comprensivo.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-1",
    word: "Wanderlust",
    pronunciation: "/ˈwändərˌləst/",
    partOfSpeech: "noun",
    definition: "A strong desire to travel and explore the world.",
    translation: "Pasión por viajar / Ganas de viajar",
    example: "Her wanderlust led her to pack a backpack and explore South America for six months.",
    exampleTranslation: "Su pasión por viajar la llevó a empacar una mochila y explorar América del Sur durante seis meses.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-2",
    word: "Itinerary",
    pronunciation: "/īˈtinəˌrerē/",
    partOfSpeech: "noun",
    definition: "A planned route or journey schedule.",
    translation: "Itinerario",
    example: "We must review our travel itinerary to make sure we don't miss our train connections.",
    exampleTranslation: "Debemos revisar nuestro itinerario de viaje para asegurarnos de no perder nuestras conexiones de tren.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-3",
    word: "Lodging",
    pronunciation: "/ˈläjiŋ/",
    partOfSpeech: "noun",
    definition: "Temporary place to stay or sleep, such as a hotel or hostel.",
    translation: "Alojamiento / Hospedaje",
    example: "Finding budget-friendly lodging in the city center can be challenging during peak season.",
    exampleTranslation: "Encontrar alojamiento económico en el centro de la ciudad puede ser difícil durante la temporada alta.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-4",
    word: "Transit",
    pronunciation: "/ˈtranzət/",
    partOfSpeech: "noun",
    definition: "The carrying of people or goods from one place to another.",
    translation: "Tránsito / Transporte",
    example: "Our baggage was lost in transit between Madrid and Rome.",
    exampleTranslation: "Nuestro equipaje se perdió en tránsito entre Madrid y Roma.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  },
  {
    id: "w2-5",
    word: "Souvenir",
    pronunciation: "/ˌso͞ovəˈnir/",
    partOfSpeech: "noun",
    definition: "A thing that is kept as a reminder of a person, place, or event.",
    translation: "Recuerdo / Souvenir",
    example: "I bought a small model of the Eiffel Tower as a souvenir of my trip to Paris.",
    exampleTranslation: "Compré un pequeño modelo de la Torre Eiffel como recuerdo de mi viaje a París.",
    learned: false,
    starred: false,
    createdAt: new Date().toISOString(),
    lastReviewed: null,
    strength: 0
  }
];
